
; --------------------------------
; SPRITES DATA
; --------------------------------

_srp_lib_lo:
		.BYTE	<[_spr00]
		.BYTE	<[_spr01]
		.BYTE	<[_spr02]
		.BYTE	<[_spr03]
		.BYTE	<[_spr04]
		.BYTE	<[_spr05]
		.BYTE	<[_spr06]
		.BYTE	<[_spr07]
		.BYTE	<[_spr08]
		.BYTE	<[_spr09]
		.BYTE	<[_spr0A]
		.BYTE	<[_spr0B]
		.BYTE	<[_spr0C]
		.BYTE	<[_spr0D]
		.BYTE	<[_spr0E]
		.BYTE	<[_spr0F]
		.BYTE	<[_spr10]
		.BYTE	<[_spr11]
		.BYTE	<[_spr12]
		.BYTE	<[_spr13]
		.BYTE	<[byte_52210]
		.BYTE	<[byte_52230]
		.BYTE	<[byte_52250]
		.BYTE	<[byte_52270]
		.BYTE	<[byte_52290]
		.BYTE	<[byte_522B0]
		.BYTE	<[byte_522D0]
		.BYTE	<[byte_522F0]
		.BYTE	<[byte_52310]
		.BYTE	<[byte_52330]
		.BYTE	<[byte_52350]
		.BYTE	<[byte_52370]
		.BYTE	<[_spr20]
		.BYTE	<[byte_523B0]
		.BYTE	<[byte_523D0]
		.BYTE	<[byte_523F0]
		.BYTE	<[byte_52410]
		.BYTE	<[byte_52430]
		.BYTE	<[byte_5244A]
		.BYTE	<[byte_5246A]
		.BYTE	<[byte_5248A]
		.BYTE	<[byte_524AA]
		.BYTE	<[byte_524CA]
		.BYTE	<[byte_524EA]
		.BYTE	<[byte_5250A]
		.BYTE	<[byte_5252A]
		.BYTE	<[byte_5254A]
		.BYTE	<[byte_5256A]
		.BYTE	<[_spr30]
		.BYTE	<[byte_52598]
		.BYTE	<[byte_525A6]
		.BYTE	<[byte_525B4]
		.BYTE	<[byte_525C2]
		.BYTE	<[byte_525D0]
		.BYTE	<[byte_525DE]
		.BYTE	<[byte_525EC]
		.BYTE	<[byte_525FA]
		.BYTE	<[byte_5261A]
		.BYTE	<[byte_5263A]
		.BYTE	<[byte_5265A]
		.BYTE	<[byte_5267A]
		.BYTE	<[byte_5269A]
		.BYTE	<[byte_526BA]
		.BYTE	<[byte_526DA]
		.BYTE	<[_spr40]
		.BYTE	<[byte_5271A]
		.BYTE	<[byte_5273A]
		.BYTE	<[byte_5275A]
		.BYTE	<[byte_5277A]
		.BYTE	<[byte_52788]
		.BYTE	<[byte_52796]
		.BYTE	<[byte_527A4]
		.BYTE	<[byte_527B2]
		.BYTE	<[byte_527C0]
		.BYTE	<[byte_527CE]
		.BYTE	<[byte_527DC]
		.BYTE	<[byte_527EA]
		.BYTE	<[byte_527F8]
		.BYTE	<[byte_52806]
		.BYTE	<[byte_52814]
		.BYTE	<[_spr50]
		.BYTE	<[byte_52830]
		.BYTE	<[byte_5283E]
		.BYTE	<[byte_5284C]
		.BYTE	<[byte_5285A]
		.BYTE	<[byte_5287A]
		.BYTE	<[byte_5289A]
		.BYTE	<[byte_528BA]
		.BYTE	<[byte_528DA]
		.BYTE	<[byte_528FA]
		.BYTE	<[byte_52900]
		.BYTE	<[byte_52920]
		.BYTE	<[byte_52940]
		.BYTE	<[byte_52960]
		.BYTE	<[byte_52980]
		.BYTE	<[byte_529A0]
		.BYTE	<[_spr60]
		.BYTE	<[byte_529E0]
		.BYTE	<[byte_529EE]
		.BYTE	<[byte_529FC]
		.BYTE	<[byte_52A0A]
		.BYTE	<[byte_52A18]
		.BYTE	<[byte_52A38]
		.BYTE	<[byte_52A58]
		.BYTE	<[byte_52A78]
		.BYTE	<[byte_52A98]
		.BYTE	<[byte_52AA6]
		.BYTE	<[byte_52AB4]
		.BYTE	<[byte_52AC2]
		.BYTE	<[_spr6D_unused]
		.BYTE	<[_spr6E_unused]
		.BYTE	<[_spr6F_unused]
		.BYTE	<[_spr70_unused]
		.BYTE	<[byte_52B08]
		.BYTE	<[byte_52B28]
		.BYTE	<[byte_52B48]
		.BYTE	<[byte_52B68]
		.BYTE	<[byte_52B88]
		.BYTE	<[byte_52BA8]
		.BYTE	<[byte_52BC8]
		.BYTE	<[byte_52BE8]
		.BYTE	<[byte_52C08]
		.BYTE	<[byte_52C28]
		.BYTE	<[byte_52C48]
		.BYTE	<[byte_52C68]
		.BYTE	<[byte_52C88]
		.BYTE	<[byte_52CA8]
		.BYTE	<[byte_52CC8]
		.BYTE	<[byte_52CE8]
		.BYTE	<[byte_52D08]
		.BYTE	<[byte_52D28]
		.BYTE	<[byte_52D48]
		.BYTE	<[byte_52D68]
		.BYTE	<[byte_52D88]
		.BYTE	<[byte_52DA8]
		.BYTE	<[byte_52DC8]
		.BYTE	<[byte_52DE8]
		.BYTE	<[byte_52E22]
		.BYTE	<[byte_52E5C]
		.BYTE	<[byte_52E96]
		.BYTE	<[byte_52ED0]
		.BYTE	<[byte_52ED8]
		.BYTE	<[byte_52EE0]
		.BYTE	<[byte_52EE8]
		.BYTE	<[byte_52EF0]
		.BYTE	<[byte_52EF8]
		.BYTE	<[byte_52EFC]
		.BYTE	<[byte_52F00]
		.BYTE	<[byte_52F05]
		.BYTE	<[byte_52F25]
		.BYTE	<[byte_52F45]
		.BYTE	<[byte_52F65]
		.BYTE	<[byte_52F85]
		.BYTE	<[byte_52FA5]
		.BYTE	<[byte_52FC5]
		.BYTE	<[byte_52FE5]
		.BYTE	<[byte_53005]
		.BYTE	<[byte_53025]
		.BYTE	<[byte_53045]
		.BYTE	<[byte_5304B]
		.BYTE	<[byte_53051]
		.BYTE	<[byte_53057]
		.BYTE	<[byte_5305D]
		.BYTE	<[byte_5307D]
		.BYTE	<[byte_5309D]
		.BYTE	<[byte_530BD]
		.BYTE	<[byte_530DD]
		.BYTE	<[byte_530FD]
		.BYTE	<[byte_5311D]
		.BYTE	<[byte_5313D]
		.BYTE	<[byte_5315D]
		.BYTE	<[byte_5317D]
		.BYTE	<[byte_53182]
		.BYTE	<[byte_5318A]
		.BYTE	<[byte_53198]
		.BYTE	<[byte_531A6]
		.BYTE	<[byte_531B4]
		.BYTE	<[byte_531C2]
		.BYTE	<[byte_531E2]
		.BYTE	<[byte_53202]
		.BYTE	<[byte_53222]
		.BYTE	<[byte_53242]
		.BYTE	<[byte_53262]
		.BYTE	<[byte_53282]
		.BYTE	<[byte_532A2]
		.BYTE	<[byte_532C2]
		.BYTE	<[byte_532E2]
		.BYTE	<[byte_53302]
		.BYTE	<[byte_53322]
_srp_lib_hi:
		.BYTE	>[_spr00]
		.BYTE	>[_spr01]
		.BYTE	>[_spr02]
		.BYTE	>[_spr03]
		.BYTE	>[_spr04]
		.BYTE	>[_spr05]
		.BYTE	>[_spr06]
		.BYTE	>[_spr07]
		.BYTE	>[_spr08]
		.BYTE	>[_spr09]
		.BYTE	>[_spr0A]
		.BYTE	>[_spr0B]
		.BYTE	>[_spr0C]
		.BYTE	>[_spr0D]
		.BYTE	>[_spr0E]
		.BYTE	>[_spr0F]
		.BYTE	>[_spr10]
		.BYTE	>[_spr11]
		.BYTE	>[_spr12]
		.BYTE	>[_spr13]
		.BYTE	>[byte_52210]
		.BYTE	>[byte_52230]
		.BYTE	>[byte_52250]
		.BYTE	>[byte_52270]
		.BYTE	>[byte_52290]
		.BYTE	>[byte_522B0]
		.BYTE	>[byte_522D0]
		.BYTE	>[byte_522F0]
		.BYTE	>[byte_52310]
		.BYTE	>[byte_52330]
		.BYTE	>[byte_52350]
		.BYTE	>[byte_52370]
		.BYTE	>[_spr20]
		.BYTE	>[byte_523B0]
		.BYTE	>[byte_523D0]
		.BYTE	>[byte_523F0]
		.BYTE	>[byte_52410]
		.BYTE	>[byte_52430]
		.BYTE	>[byte_5244A]
		.BYTE	>[byte_5246A]
		.BYTE	>[byte_5248A]
		.BYTE	>[byte_524AA]
		.BYTE	>[byte_524CA]
		.BYTE	>[byte_524EA]
		.BYTE	>[byte_5250A]
		.BYTE	>[byte_5252A]
		.BYTE	>[byte_5254A]
		.BYTE	>[byte_5256A]
		.BYTE	>[_spr30]
		.BYTE	>[byte_52598]
		.BYTE	>[byte_525A6]
		.BYTE	>[byte_525B4]
		.BYTE	>[byte_525C2]
		.BYTE	>[byte_525D0]
		.BYTE	>[byte_525DE]
		.BYTE	>[byte_525EC]
		.BYTE	>[byte_525FA]
		.BYTE	>[byte_5261A]
		.BYTE	>[byte_5263A]
		.BYTE	>[byte_5265A]
		.BYTE	>[byte_5267A]
		.BYTE	>[byte_5269A]
		.BYTE	>[byte_526BA]
		.BYTE	>[byte_526DA]
		.BYTE	>[_spr40]
		.BYTE	>[byte_5271A]
		.BYTE	>[byte_5273A]
		.BYTE	>[byte_5275A]
		.BYTE	>[byte_5277A]
		.BYTE	>[byte_52788]
		.BYTE	>[byte_52796]
		.BYTE	>[byte_527A4]
		.BYTE	>[byte_527B2]
		.BYTE	>[byte_527C0]
		.BYTE	>[byte_527CE]
		.BYTE	>[byte_527DC]
		.BYTE	>[byte_527EA]
		.BYTE	>[byte_527F8]
		.BYTE	>[byte_52806]
		.BYTE	>[byte_52814]
		.BYTE	>[_spr50]
		.BYTE	>[byte_52830]
		.BYTE	>[byte_5283E]
		.BYTE	>[byte_5284C]
		.BYTE	>[byte_5285A]
		.BYTE	>[byte_5287A]
		.BYTE	>[byte_5289A]
		.BYTE	>[byte_528BA]
		.BYTE	>[byte_528DA]
		.BYTE	>[byte_528FA]
		.BYTE	>[byte_52900]
		.BYTE	>[byte_52920]
		.BYTE	>[byte_52940]
		.BYTE	>[byte_52960]
		.BYTE	>[byte_52980]
		.BYTE	>[byte_529A0]
		.BYTE	>[_spr60]
		.BYTE	>[byte_529E0]
		.BYTE	>[byte_529EE]
		.BYTE	>[byte_529FC]
		.BYTE	>[byte_52A0A]
		.BYTE	>[byte_52A18]
		.BYTE	>[byte_52A38]
		.BYTE	>[byte_52A58]
		.BYTE	>[byte_52A78]
		.BYTE	>[byte_52A98]
		.BYTE	>[byte_52AA6]
		.BYTE	>[byte_52AB4]
		.BYTE	>[byte_52AC2]
		.BYTE	>[_spr6D_unused]
		.BYTE	>[_spr6E_unused]
		.BYTE	>[_spr6F_unused]
		.BYTE	>[_spr70_unused]
		.BYTE	>[byte_52B08]
		.BYTE	>[byte_52B28]
		.BYTE	>[byte_52B48]
		.BYTE	>[byte_52B68]
		.BYTE	>[byte_52B88]
		.BYTE	>[byte_52BA8]
		.BYTE	>[byte_52BC8]
		.BYTE	>[byte_52BE8]
		.BYTE	>[byte_52C08]
		.BYTE	>[byte_52C28]
		.BYTE	>[byte_52C48]
		.BYTE	>[byte_52C68]
		.BYTE	>[byte_52C88]
		.BYTE	>[byte_52CA8]
		.BYTE	>[byte_52CC8]
		.BYTE	>[byte_52CE8]
		.BYTE	>[byte_52D08]
		.BYTE	>[byte_52D28]
		.BYTE	>[byte_52D48]
		.BYTE	>[byte_52D68]
		.BYTE	>[byte_52D88]
		.BYTE	>[byte_52DA8]
		.BYTE	>[byte_52DC8]
		.BYTE	>[byte_52DE8]
		.BYTE	>[byte_52E22]
		.BYTE	>[byte_52E5C]
		.BYTE	>[byte_52E96]
		.BYTE	>[byte_52ED0]
		.BYTE	>[byte_52ED8]
		.BYTE	>[byte_52EE0]
		.BYTE	>[byte_52EE8]
		.BYTE	>[byte_52EF0]
		.BYTE	>[byte_52EF8]
		.BYTE	>[byte_52EFC]
		.BYTE	>[byte_52F00]
		.BYTE	>[byte_52F05]
		.BYTE	>[byte_52F25]
		.BYTE	>[byte_52F45]
		.BYTE	>[byte_52F65]
		.BYTE	>[byte_52F85]
		.BYTE	>[byte_52FA5]
		.BYTE	>[byte_52FC5]
		.BYTE	>[byte_52FE5]
		.BYTE	>[byte_53005]
		.BYTE	>[byte_53025]
		.BYTE	>[byte_53045]
		.BYTE	>[byte_5304B]
		.BYTE	>[byte_53051]
		.BYTE	>[byte_53057]
		.BYTE	>[byte_5305D]
		.BYTE	>[byte_5307D]
		.BYTE	>[byte_5309D]
		.BYTE	>[byte_530BD]
		.BYTE	>[byte_530DD]
		.BYTE	>[byte_530FD]
		.BYTE	>[byte_5311D]
		.BYTE	>[byte_5313D]
		.BYTE	>[byte_5315D]
		.BYTE	>[byte_5317D]
		.BYTE	>[byte_53182]
		.BYTE	>[byte_5318A]
		.BYTE	>[byte_53198]
		.BYTE	>[byte_531A6]
		.BYTE	>[byte_531B4]
		.BYTE	>[byte_531C2]
		.BYTE	>[byte_531E2]
		.BYTE	>[byte_53202]
		.BYTE	>[byte_53222]
		.BYTE	>[byte_53242]
		.BYTE	>[byte_53262]
		.BYTE	>[byte_53282]
		.BYTE	>[byte_532A2]
		.BYTE	>[byte_532C2]
		.BYTE	>[byte_532E2]
		.BYTE	>[byte_53302]
		.BYTE	>[byte_53322]
_spr00:
		.BYTE	  1,  1
		.BYTE	  0,  1
_spr01:
		.BYTE	  2,  1
		.BYTE	  0,  2,  3
_spr02:
		.BYTE	  1,  2
		.BYTE	  0,  4
		.BYTE	  0,  5
_spr03:
		.BYTE	  1,  1,  0,  6
_spr04:
		.BYTE	  1,  1,  0,  7
_spr05:
		.BYTE	  1,  1,  0,  8
_spr06:
		.BYTE	  1,  1,  0,  8
_spr07:
		.BYTE	  1,  1,  0,  9
_spr08:
		.BYTE	  1,  1,  0, $A
_spr09:
		.BYTE	  1,  1,  0, $B
_spr0A:
		.BYTE	  1,  1,  0, $C
_spr0B:
		.BYTE	  1,  1,  0, $D
_spr0C:
		.BYTE	  1,  1,  0, $E
_spr0D:
		.BYTE	  1,  1,  0, $F
_spr0E:
		.BYTE	  1,  1,  0,$10
_spr0F:
		.BYTE	  1,  1,  0,$11
_spr10:
		.BYTE	  1,  1,  0,$12
_spr11:
		.BYTE	  1,  1,  0,$13
_spr12:
		.BYTE	  1,  1,  0,$14
_spr13:
		.BYTE	  1,  1,  0,$15
byte_52210:
		.BYTE	  4,  6
		.BYTE	$FF,  0,$16,$17,  0
		.BYTE	  1,  0,$18,$19,  0
		.BYTE	  1,$1A,$1B,$1C,  0
		.BYTE	  0,  0,$1D,$1E,  0
		.BYTE	  0,  0,$1F,$20,  0
		.BYTE	  0,  0,$21,$22,  0
byte_52230:
		.BYTE	  4,  6,$FF,  0,$23,$24,  0,  1,  0,$25,$26,  0,  1,$27,$28,$29
		.BYTE	  0,  0,  0,$2A,$2B,  0,  0,  0,$2C,$2D,$2E,  0,  0,$2F,$30,$31
byte_52250:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,  1,  0,$18,$19,  0,  1,$1A,$1B,$1C
		.BYTE	  0,  0,  0,$32,$33,  0,  0,  0,$34,$35,  0,  0,  0,$21,$36,  0
byte_52270:
		.BYTE	  4,  6,$FF,  0,$23,$24,  0,  1,  0,$37,$38,  0,  1,$39,$3A,$3B
		.BYTE	  0,  0,  0,$3C,$3D,  0,  0,  0,$3E,$3F,$2E,  0,  0,$40,$41,$42
byte_52290:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,  1,  0,$18,$19,  0,  1,$1A,$1B,$1C
		.BYTE	  0,  0,  0,$32,$33,  0,  1,  0,$43,$35,  0,  1,  0,$44,$45,  0
byte_522B0:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$46,$47,$48,  0,$FF,$49,$4A,$4B
		.BYTE	  0,  0,  0,$4C,$1E,  0,  0,  0,$1F,$20,  0,  0,  0,$21,$22,  0
byte_522D0:
		.BYTE	  4,  6,$FF,  0,$23,$24,  0,$FF,$4D,$4E,$4F,  0,$FF,$50,$51,$52
		.BYTE	  0,  0,  0,$53,$54,  0,  0,  0,$2C,$2D,$2E,  0,  0,$2F,$30,$31
byte_522F0:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$46,$47,$48,  0,$FF,$49,$4A,$4B
		.BYTE	  0,  0,  0,$55,$33,  0,  0,  0,$34,$35,  0,  0,  0,$21,$36,  0
byte_52310:
		.BYTE	  4,  6,$FF,  0,$23,$24,  0,$FF,$4D,$4E,$4F,  0,$FF,$50,$51,$52
		.BYTE	  0,  0,  0,$56,$3D,  0,  0,  0,$3E,$3F,$2E,  0,  0,$40,$41,$42
byte_52330:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$46,$47,$48,  0,$FF,$49,$4A,$4B
		.BYTE	  0,  0,  0,$55,$33,  0,  1,  0,$43,$35,  0,  1,  0,$44,$45,  0
byte_52350:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$57,$58,$59,  0,$FF,$5A,$5B,$5C
		.BYTE	  0,  0,  0,$4C,$1E,  0,  0,  0,$1F,$20,  0,  0,  0,$21,$22,  0
byte_52370:
		.BYTE	  4,  6,$FF,  0,$23,$24,  0,$FF,$5D,$5E,$5F,  0,$FF,$60,$61,$62
		.BYTE	  0,  0,  0,$53,$54,  0,  0,  0,$2C,$2D,$2E,  0,  0,$2F,$30,$31
_spr20:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$57,$58,$59,  0,$FF,$5A,$5B,$5C
		.BYTE	  0,  0,  0,$55,$33,  0,  0,  0,$34,$35,  0,  0,  0,$21,$36,  0
byte_523B0:
		.BYTE	  4,  6,$FF,  0,$23,$24,  0,$FF,$5D,$5E,$5F,  0,$FF,$60,$61,$62
		.BYTE	  0,  0,  0,$56,$3D,  0,  0,  0,$3E,$3F,$2E,  0,  0,$40,$41,$42
byte_523D0:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$57,$58,$59,  0,$FF,$5A,$5B,$5C
		.BYTE	  0,  0,  0,$55,$33,  0,  1,  0,$43,$35,  0,  1,  0,$44,$45,  0
byte_523F0:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$46,$47,$48,  0,$FF,$49,$4A,$4B
		.BYTE	  0,$FF,  0,$63,$3D,  0,$FF,  0,$64,$65,$66,$FF,  0,  0,$67,$68
byte_52410:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$57,$58,$59,  0,$FF,$5A,$5B,$5C
		.BYTE	  0,$FF,  0,$63,$3D,  0,$FF,  0,$64,$65,$66,$FF,  0,  0,$67,$68
byte_52430:
		.BYTE	  3,  6,  0,$69,$6A,  0,  0,$6B,$6C,$6D,  0,$6E,$6F,$70,  0,$71
		.BYTE	$72,$73,  0,$74,$75,$76,  0,$77,  0,$78
byte_5244A:
		.BYTE	  4,  6,$FF,  0,$23,$24,  0,$FF,$4D,$4E,$4F,  0,$FF,$50,$51,$52
		.BYTE	  0,  0,  0,$56,$3D,  0,  0,  0,$3E,$3F,$2E,  0,  0,$40,$41,$42
byte_5246A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$23,$24,  0,  0,$5D,$5E,$5F
		.BYTE	  0,  0,$60,$61,$62,  0,  0,  0,$79,$7A,  0,  0,  0,$7B,$7C,$7D
byte_5248A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,$16,$17
		.BYTE	  0,  0,$46,$47,$48,  0,  0,$49,$7E,$7F,  0,  0,  0,$80,$81,$82
byte_524AA:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,$16,$17
		.BYTE	  0,  0,$57,$58,$59,  0,  0,$5A,$83,$84,  0,  0,  0,$80,$81,$82
byte_524CA:
		.BYTE	  4,  6,$FF,$85,$23,$24,  0,$FF,$86,$87,$88,  0,$FF,  0,$89,$8A
		.BYTE	  0,  0,  0,$53,$54,  0,  0,  0,$2C,$2D,$2E,  0,  0,$2F,$30,$31
byte_524EA:
		.BYTE	  4,  6,$FF,$8B,$23,$24,  0,$FF,$8C,$8D,$8E,  0,$FF,  0,$8F,$90
		.BYTE	  0,  0,  0,$53,$54,  0,  0,  0,$2C,$2D,$2E,  0,  0,$2F,$30,$31
byte_5250A:
		.BYTE	  4,  6,$FF,  0,$23,$24,  0,  1,  0,$25,$91,  0,  1,$27,$92,$93
		.BYTE	  0,  0,$94,$95,$96,  0,  0,  0,$2C,$2D,$2E,  0,  0,$2F,$30,$31
byte_5252A:
		.BYTE	  4,  6,$FF,  0,$23,$24,  0,  1,  0,$25,$26,  0,  1,$27,$28,$29
		.BYTE	  0,  0,  0,$2A,$2B,  0,  0,  0,$2C,$2D,$2E,  0,  0,$2F,$30,$31
byte_5254A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$98,$99,$9A,  0,  0,$9B,$9C
		.BYTE	  0,  0,  0,$9D,$9E,  0,  0,  0,$9F,$A0,  0,  0,  0,$A1,$A2,  0
byte_5256A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$A3,$A4,  0,  0,  0,$9B,$A5
		.BYTE	  0,  0,  0,$9D,$9E,  0,  0,  0,$9F,$A0,  0,  0,  0,$A1,$A2,  0
_spr30:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,$A6,$A7,$A8
byte_52598:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,$A9,$AA,$AB,  0,$AC,$AD,$AE
byte_525A6:
		.BYTE	  3,  3,  0,$AF,$B0,$B1,  0,$B2,$B3,$B4,  0,$B5,$B6,$B7
byte_525B4:
		.BYTE	  3,  3,  0,$AF,$B0,$B1,  0,$B8,$B3,$B4,  0,$B9,$BA,$BB
byte_525C2:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,$A6,$A7,$A8
byte_525D0:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,$A9,$AA,$AB,  0,$AC,$AD,$AE
byte_525DE:
		.BYTE	  3,  3,  0,$BC,$BD,  0,  0,$BE,$BF,$C0,  0,$C1,$B6,$B7
byte_525EC:
		.BYTE	  3,  3,  0,$BC,$BD,  0,  0,$C2,$BF,$C0,  0,$C3,$BA,$C4
byte_525FA:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$C5,$C6,  0,  0,  0,$C7,$C8
		.BYTE	  0,  0,  0,$C9,$CA,  0,  0,  0,$CB,$CC,  0,  0,  0,$CD,$CE,  0
byte_5261A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$CF,$D0,  0,  0,  0,$D1,$D2
		.BYTE	  0,  0,  0,$D3,$D4,  0,  0,  0,$D5,$D6,  0,  0,  0,$D7,$D8,$D9
byte_5263A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$C5,$C6,  0,  0,  0,$C7,$C8
		.BYTE	  0,  0,  0,$C9,$CA,  0,  0,  0,$DA,$DB,  0,  0,  0,$CD,$DC,  0
byte_5265A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$CF,$DD,  0,  0,  0,$DE,$DF
		.BYTE	  0,  0,  0,$E0,$E1,  0,  0,  0,$E2,$E3,  0,  0,  0,$E4,$E5,$D9
byte_5267A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$CF,$D0,  0,  0,$E6,$E7,$E8
		.BYTE	  0,  0,  0,$E9,$EA,  0,  0,  0,$D5,$D6,  0,  0,  0,$D7,$D8,$D9
byte_5269A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$CF,$D0,  0,  0,$E6,$E7,$E8
		.BYTE	  0,  0,$EB,$EC,$ED,  0,  0,$EE,$EF,$F0,  0,  0,  0,  0,$CE,  0
byte_526BA:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$F1,$F2,  0,  0,  0,$C7,$F3
		.BYTE	  0,  0,  0,$C9,$CA,  0,  0,  0,$CB,$CC,  0,  0,  0,$CD,$CE,  0
byte_526DA:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$F4,$F5,  0,  0,  0,$D1,$F6
		.BYTE	  0,  0,  0,$D3,$D4,  0,  0,  0,$D5,$D6,  0,  0,  0,$D7,$D8,$D9
_spr40:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$F1,$F2,  0,  0,  0,$C7,$F3
		.BYTE	  0,  0,  0,$C9,$CA,  0,  0,  0,$DA,$DB,  0,  0,  0,$CD,$DC,  0
byte_5271A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$F4,$F5,  0,  0,  0,$F7,$F8
		.BYTE	  0,  0,  0,$E0,$E1,  0,  0,  0,$E2,$E3,  0,  0,  0,$E4,$E5,$D9
byte_5273A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$F4,$F5,  0,  0,$E6,$F9,$FA
		.BYTE	  0,  0,  0,$E9,$EA,  0,  0,  0,$D5,$D6,  0,  0,  0,$D7,$D8,$D9
byte_5275A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$F4,$F5,  0,  0,$E6,$F9,$FA
		.BYTE	  0,  0,$EB,$EC,$ED,  0,  0,$EE,$EF,$F0,  0,  0,  0,  0,$CE,  0
byte_5277A:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,$A6
byte_52788:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,  0,$A7,$A8,  0,  0,$A9,$AA
byte_52796:
		.BYTE	  3,  3,  0,  0,$AB,$AC,  0,  0,$AD,$AE,  0,$AF,$B0,$B1
byte_527A4:
		.BYTE	  3,  3,  0,  0,$AB,$AC,  0,  0,$B2,$B3,  0,$B4,$B5,$B6
byte_527B2:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,$A6
byte_527C0:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,  0,$A7,$A8,  0,  0,$A9,$AA
byte_527CE:
		.BYTE	  3,  3,  0,$AB,$AC,$B7,  0,$B8,$B9,$BA,  0,$BB,$BC,$BD
byte_527DC:
		.BYTE	  3,  3,  0,$BE,$BF,$C0,  0,  0,$C1,$C2,  0,  0,$C3,$C4
byte_527EA:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,$C5
byte_527F8:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,  0,$C6,$C7,  0,  0,$A9,$AA
byte_52806:
		.BYTE	  3,  3,  0,  0,$C8,$C9,  0,  0,$AD,$CA,  0,$AF,$B0,$B1
byte_52814:
		.BYTE	  3,  3,  0,  0,$C8,$C9,  0,  0,$B2,$CB,  0,$B4,$B5,$B6
_spr50:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,$C5
byte_52830:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,  0,$C6,$C7,  0,  0,$A9,$AA
byte_5283E:
		.BYTE	  3,  3,  0,$C8,$C9,$B7,  0,$B8,$CC,$BA,  0,$BB,$BC,$BD
byte_5284C:
		.BYTE	  3,  3,  0,$BE,$CD,$CE,  0,  0,$C1,$C2,  0,  0,$C3,$C4
byte_5285A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$CF,$D0,  0,  0,  0,$D1,$D2
		.BYTE	  0,  0,  0,$D3,$D4,  0,  0,  0,$D5,$D6,  0,  0,  0,$D7,$D8,  0
byte_5287A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$D9,$DA,  0,  0,  0,$DB,$DC
		.BYTE	  0,  0,  0,$DD,$DE,  0,  0,  0,$DF,$E0,  0,  0,  0,$E1,$E2,$E3
byte_5289A:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$CF,$D0,  0,  0,  0,$D1,$D2
		.BYTE	  0,  0,  0,$E4,$E5,  0,  0,  0,$E6,$E7,  0,  0,  0,$D7,$E8,  0
byte_528BA:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$D9,$E9,  0,  0,  0,$EA,$EB
		.BYTE	  0,  0,  0,$EC,$ED,  0,  0,  0,$EE,$EF,  0,  0,  0,$F0,$F1,$E3
byte_528DA:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,$F2,$F3
		.BYTE	  0,  0,$F4,$F5,$F6,  0,  0,$F7,$F8,$F9,  0,  0,  0,$FA,$FB,$FC
byte_528FA:
		.BYTE	  3,  1,  0,$15,$15,$15
byte_52900:
		.BYTE	  4,  6,  0,$97,  0,  0,  0,  0,$98,$99,$9A,  0,  0,$9B,$9C,$9D
		.BYTE	  0,  0,  0,$9E,$9F,  0,  0,  0,$A0,$A1,  0,  0,  0,$A2,$A3,  0
byte_52920:
		.BYTE	  4,  6,  0,$A4,$A5,  0,  0,  0,$A6,$A7,$A8,  0,  0,$A9,$AA,$AB
		.BYTE	  0,  0,  0,$AC,$AD,  0,  0,  0,$AE,$AF,  0,  0,  0,$B0,$B1,$B2
byte_52940:
		.BYTE	  4,  6,  0,$97,  0,  0,  0,  0,$98,$99,$9A,  0,  0,$9B,$9C,$9D
		.BYTE	  0,  0,  0,$9E,$9F,  0,  0,  0,$B3,$B4,  0,  0,  0,$A2,$B5,  0
byte_52960:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,$B6,$B7,$A8,  0,  0,$B8,$B9,$BA
		.BYTE	  0,  0,  0,$BB,$BC,  0,  0,  0,$BD,$BE,  0,  0,  0,$BF,$C0,$C1
byte_52980:
		.BYTE	  4,  6,  0,  0,  0,  0,$C2,  0,  0,$C3,$C4,$C5,  0,  0,$C6,$C7
		.BYTE	$C8,  0,  0,$C9,$CA,  0,  0,  0,$CB,$CC,$CD,  0,$CE,$CF,$D0,$D1
byte_529A0:
		.BYTE	  4,  6,  0,  0,  0,  0,$D2,  0,  0,$D3,$D4,$D5,  0,  0,$D6,$D7
		.BYTE	  0,  0,$D8,$D9,$DA,  0,  0,$DB,$DC,$DD,  0,  0,$DE,$DF,$E0,$E1
_spr60:
		.BYTE	  4,  6
		.BYTE	  0,  0,  0,  0,  0
		.BYTE	  0,$E2,$E3,  0,  0
		.BYTE	  0,$E4,$E5,$E6,  0
		.BYTE	  0,$E7,$E8,$E9,$EA
		.BYTE	  0,  0,$EB,$EC,  0
		.BYTE	  0,  0,$ED,$EE,$EF
byte_529E0:
		.BYTE	  3,  3
		.BYTE	  0,$F0,$F1,$F2
		.BYTE	  0,$F3,$F4,$F5
		.BYTE	  0,  0,$F6,$F7
byte_529EE:
		.BYTE	  3,  3
		.BYTE	  0,$F8,$F9,$FA
		.BYTE	  0,$FB,$FC,$FD
		.BYTE	  0,$FE,$FF,  0
byte_529FC:
		.BYTE	  3,  3,  0,  0,$F6,$F7,  0,$F3,$F4,$F5,  0,$F0,$F1,$F2
byte_52A0A:
		.BYTE	  3,  3,  0,$FE,$FF,  0,  0,$FB,$FC,$FD,  0,$F8,$F9,$FA
byte_52A18:
		.BYTE	  4,  6,  0,  0,$98,  0,  0,  0,  0,$99,$9A,  0,  0,  0,$9B,$9C
		.BYTE	  0,  0,$9D,$9E,$9F,  0,  0,  0,$A0,$A1,  0,  0,  0,$A2,$A3,  0
byte_52A38:
		.BYTE	  4,  6,  0,  0,$98,  0,  0,  0,  0,$99,$9A,  0,  0,  0,$A4,$A5
		.BYTE	  0,  0,$A6,$A7,$9F,  0,  0,  0,$A0,$A1,  0,  0,  0,$A2,$A3,  0
byte_52A58:
		.BYTE	  4,  6,  0,  0,$98,  0,  0,  0,  0,$A8,$A9,  0,  0,  0,$AA,$AB
		.BYTE	  0,  0,$9D,$9E,$9F,  0,  0,  0,$A0,$A1,  0,  0,  0,$A2,$A3,  0
byte_52A78:
		.BYTE	  4,  6,  0,  0,$98,  0,  0,  0,  0,$A8,$A9,  0,  0,  0,$AC,$AD
		.BYTE	  0,  0,$A6,$A7,$9F,  0,  0,  0,$A0,$A1,  0,  0,  0,$A2,$A3,  0
byte_52A98:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,$AE,$AF
byte_52AA6:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,$B0,$B1,  0,  0,$B2,$B3,$B4
byte_52AB4:
		.BYTE	  3,  3,  0,  0,$B5,  0,  0,  0,$B6,$B7,  0,$B8,$B9,$BA
byte_52AC2:
		.BYTE	  3,  3,  0,  0,$B5,  0,  0,  0,$B6,$B7,  0,$BB,$BC,$BD
_spr6D_unused:
		.BYTE	  3,  3
		.BYTE	  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0
		.BYTE	  0,  0,$AE,$AF
_spr6E_unused:
		.BYTE	  3,  3
		.BYTE	  0,  0,  0,  0
		.BYTE	  0,$BE,$BF,  0
		.BYTE	  0,$B2,$C0,$B4
_spr6F_unused:
		.BYTE	  3,  3
		.BYTE	  0,  0,$B5,  0
		.BYTE	  0,  0,$C1,$C2
		.BYTE	  0,$B8,$B9,$BA
_spr70_unused:
		.BYTE	  3,  3
		.BYTE	  0,  0,$B5,  0
		.BYTE	  0,  0,$C1,$C2
		.BYTE	  0,$BB,$BC,$BD
byte_52B08:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$C3,$C4,  0,  0,  0,$C5,$C6
		.BYTE	  0,  0,  0,$C7,$C8,  0,  0,  0,$C9,$CA,  0,  0,  0,$CB,$CC,  0
byte_52B28:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$CD,$CE,  0,  0,  0,$CF,$D0
		.BYTE	  0,  0,  0,$D1,$D2,  0,  0,  0,$D3,$D4,  0,  0,  0,$D5,$D6,$D7
byte_52B48:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$C3,$C4,  0,  0,  0,$D8,$D9
		.BYTE	  0,  0,  0,$DA,$DB,  0,  0,  0,$DC,$DD,  0,  0,  0,$CB,$DE,  0
byte_52B68:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$CD,$CE,  0,  0,  0,$DF,$E0
		.BYTE	  0,  0,  0,$E1,$E2,  0,  0,  0,$E3,$E4,  0,  0,  0,$E5,$E6,$D7
byte_52B88:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$CD,$CE,  0,  0,$E7,$E8,$E9
		.BYTE	  0,  0,  0,$EA,$EB,  0,  0,  0,$EC,$ED,  0,  0,  0,$D5,$D6,$D7
byte_52BA8:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$CD,$EE,  0,  0,$E7,$E8,$EF
		.BYTE	  0,  0,$F0,$F1,$F2,  0,  0,$F3,$F4,$F5,  0,  0,  0,  0,$F6,  0
byte_52BC8:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$F7,$F8,  0,  0,  0,$F9,$C6
		.BYTE	  0,  0,  0,$C7,$C8,  0,  0,  0,$C9,$CA,  0,  0,  0,$CB,$CC,  0
byte_52BE8:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$FA,$FB,  0,  0,  0,$FC,$D0
		.BYTE	  0,  0,  0,$D1,$D2,  0,  0,  0,$D3,$D4,  0,  0,  0,$D5,$D6,$D7
byte_52C08:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$F7,$F8,  0,  0,  0,$FD,$D9
		.BYTE	  0,  0,  0,$DA,$DB,  0,  0,  0,$DC,$DD,  0,  0,  0,$CB,$DE,  0
byte_52C28:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$FA,$FB,  0,  0,  0,$FE,$E0
		.BYTE	  0,  0,  0,$E1,$E2,  0,  0,  0,$E3,$E4,  0,  0,  0,$E5,$E6,$D7
byte_52C48:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$FA,$FB,  0,  0,$E7,$FF,$E9
		.BYTE	  0,  0,  0,$EA,$EB,  0,  0,  0,$EC,$ED,  0,  0,  0,$D5,$D6,$D7
byte_52C68:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$FA,$FB,  0,  0,$E7,$FF,$EF
		.BYTE	  0,  0,$F0,$F1,$F2,  0,  0,$F3,$F4,$F5,  0,  0,  0,  0,$F6,  0
byte_52C88:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$AE,$AF,  0,  0,  0,$B0,$B1
		.BYTE	  0,  0,  0,$B2,$B3,  0,  0,  0,$B4,$B5,  0,  0,  0,$B6,$B7,  0
byte_52CA8:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$B8,$B9,  0,  0,  0,$BA,$BB
		.BYTE	  0,  0,  0,$BC,$BD,  0,  0,  0,$BE,$BF,  0,  0,  0,$C0,$C1,$C2
byte_52CC8:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$AE,$AF,  0,  0,  0,$C3,$C4
		.BYTE	  0,  0,  0,$C5,$C6,  0,  0,  0,$C7,$C8,  0,  0,  0,$B6,$C9,  0
byte_52CE8:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$B8,$B9,  0,  0,  0,$CA,$CB
		.BYTE	  0,  0,  0,$CC,$CD,  0,  0,  0,$CE,$CF,  0,  0,  0,$D0,$D1,$C2
byte_52D08:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$D2,$D3,$D4,  0,$D5,$D6,$D7
		.BYTE	$D8,  0,$D9,$DA,$DB,$DC,  0,  0,$BE,$DD,  0,  0,  0,$C0,$C1,$C2
byte_52D28:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,$DE,$DF,$E0,  0,  0,$E1,$E2,$E3
		.BYTE	  0,  0,$E4,$E5,$E6,  0,  0,  0,$BE,$DD,  0,  0,  0,$C0,$C1,$C2
byte_52D48:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$E7,$E8,  0,  0,  0,$E9,$EA
		.BYTE	  0,  0,  0,$EB,$EC,  0,  0,  0,$B4,$B5,  0,  0,  0,$B6,$B7,  0
byte_52D68:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$ED,$EE,  0,  0,  0,$EF,$F0
		.BYTE	  0,  0,  0,$F1,$F2,  0,  0,  0,$BE,$BF,  0,  0,  0,$C0,$C1,$C2
byte_52D88:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$E7,$E8,  0,  0,  0,$E9,$EA
		.BYTE	  0,  0,  0,$F3,$F4,  0,  0,  0,$C7,$C8,  0,  0,  0,$B6,$C9,  0
byte_52DA8:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$ED,$EE,  0,  0,  0,$EF,$F0
		.BYTE	  0,  0,  0,$F5,$F6,  0,  0,  0,$CE,$CF,  0,  0,  0,$D0,$D1,$C2
byte_52DC8:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,$A8,$A9
		.BYTE	  0,  0,$F7,$F8,$F9,  0,  0,  0,$FA,$FB,  0,  0,  0,$FC,$FD,$FE
byte_52DE8:
		.BYTE	  7,  7,  0,  0,$97,$98,$99,$9A,$9B,  0,  0,  0,$9C,$9D,$9E,$9F
		.BYTE	$A0,$A1,  0,  0,$A2,$A3,$A4,$A5,  0,  0,  0,  0,$A8,$A9,$AA,$AB
		.BYTE	  0,  0,  0,$AE,$AF,$B0,$B1,$B2,  0,  0,  0,  0,$B3,$B4,$B5,$B6
		.BYTE	  0,  0,  0,  0,$B7,$B8,$B9,$BA,$BB,  0
byte_52E22:
		.BYTE	  7,  7
		.BYTE	  0,  0,$97,$98,$99,$9A,$9B,  0
		.BYTE	  0,  0,$9C,$9D,$9E,$9F,$A0,$A1
		.BYTE	  0,  0,$A2,$A3,$A4,$A5,  0,  0
		.BYTE	  0,  0,$BC,$BD,$AA,$AB,  0,  0
		.BYTE	  0,  0,$BE,$BF,$C0,$B2,  0,  0
		.BYTE	  0,  0,$C1,$C2,$C3,$C4,  0,  0
		.BYTE	  0,  0,  0,$C5,$C6,$C7,  0,  0
byte_52E5C:
		.BYTE	  7,  7
		.BYTE	  0,  0,$97,$98,$99,$9A,$9B,  0
		.BYTE	  0,  0,$9C,$9D,$9E,$9F,$A0,$A1
		.BYTE	  0,  0,$A2,$A3,$A4,$A5,  0,  0
		.BYTE	  0,$C8,$C9,$CA,$AA,$AB,  0,  0
		.BYTE	  0,$CB,$CC,$CD,$CE,$B2,  0,  0
		.BYTE	  0,  0,$CF,$D0,$D1,$D2,  0,  0
		.BYTE	  0,  0,$D3,$D4,$D5,$D6,$D7,  0
byte_52E96:
		.BYTE	  7,  7
		.BYTE	  0,  0,$97,$98,$99,$9A,$9B,  0
		.BYTE	  0,  0,$9C,$9D,$9E,$9F,$A0,$A1
		.BYTE	  0,  0,$A2,$A3,$A4,$A5,  0,  0
		.BYTE	  0,  0,$D8,$D9,$AA,$AB,  0,  0
		.BYTE	  0,  0,$DA,$DB,$DC,$B2,  0,  0
		.BYTE	  0,  0,$DD,$DE,$DF,$E0,  0,  0
		.BYTE	  0,  0,  0,$E1,$E2,$E3,  0,  0
byte_52ED0:
		.BYTE	  2,  2,  0,$A6,$A7,  0,$AC,$AD
byte_52ED8:
		.BYTE	  2,  2,  0,$A6,$E4,  0,$AC,$E5
byte_52EE0:
		.BYTE	  2,  2,  0,$A6,$E6,  0,$AC,$E7
byte_52EE8:
		.BYTE	  2,  2,  0,$A6,$A7,  0,$E8,$E9
byte_52EF0:
		.BYTE	  2,  2,  0,$A6,$A7,  0,$EA,$EB
byte_52EF8:
		.BYTE	  1,  1,  0,$EC
byte_52EFC:
		.BYTE	  1,  1,  0,$ED
byte_52F00:
		.BYTE	  2,  1,  0,$EE,$EF
byte_52F05:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$18,$19,$1A,$1B,$FF,$1C,$1D,$1E
		.BYTE	$1F,  0,  0,$20,$21,$22,  0,  0,$23,$24,  0,  0,  0,$25,$26,$27
byte_52F25:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$28,$29,$2A,$1B,$FF,$2B,$2C,$2D
		.BYTE	$1F,  0,  0,$20,$21,$22,  0,  0,$23,$24,  0,  0,  0,$25,$26,$27
byte_52F45:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$18,$19,$1A,$1B,$FF,$1C,$1D,$1E
		.BYTE	$1F,  0,  0,$2E,$2F,$22,  0,  0,$30,$31,  0,  0,  0,$32,$33,  0
byte_52F65:
		.BYTE	  4,  6,$FF,  0,$34,$35,  0,$FF,$36,$37,$38,$39,$FF,$3A,$3B,$3C
		.BYTE	$3D,  0,  0,$3E,$3F,$40,  0,  0,$41,$42,$43,  0,  0,$44,$45,$46
byte_52F85:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$18,$19,$1A,$1B,$FF,$1C,$1D,$1E
		.BYTE	$1F,  0,  0,$47,$48,$22,  0,  0,$49,$4A,  0,  0,  0,$32,$4B,  0
byte_52FA5:
		.BYTE	  4,  6,$FF,  0,$34,$35,  0,$FF,$36,$37,$38,$39,$FF,$3A,$3B,$3C
		.BYTE	$3D,  0,  0,$4C,$4D,$40,  0,  0,$4E,$4F,$43,  0,  0,$50,$51,$52
byte_52FC5:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$28,$29,$2A,$1B,$FF,$2B,$53,$2D
		.BYTE	$1F,  0,  0,$2E,$2F,$22,  0,  0,$30,$31,  0,  0,  0,$32,$33,  0
byte_52FE5:
		.BYTE	  4,  6,$FF,  0,$34,$35,  0,$FF,$54,$55,$56,$39,$FF,$57,$58,$59
		.BYTE	$3D,  0,  0,$5A,$5B,$40,  0,  0,$41,$42,$43,  0,  0,$44,$45,$46
byte_53005:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,$FF,$28,$29,$2A,$1B,$FF,$2B,$2C,$2D
		.BYTE	$1F,  0,  0,$47,$48,$22,  0,  0,$49,$4A,  0,  0,  0,$32,$4B,  0
byte_53025:
		.BYTE	  4,  6,$FF,  0,$34,$35,  0,$FF,$54,$55,$56,$39,$FF,$57,$58,$59
		.BYTE	$3D,  0,  0,$5C,$5D,$40,  0,  0,$4E,$4F,$43,  0,  0,$50,$51,$52
byte_53045:
		.BYTE	  1,  2,  0,$5E,  0,$5F
byte_5304B:
		.BYTE	  1,  2,  0,$60,  0,$61
byte_53051:
		.BYTE	  1,  2,  0,$62,  0,$63
byte_53057:
		.BYTE	  1,  2,  0,$64,  0,$65
byte_5305D:
		.BYTE	  4,  6,$FF,  0,$34,$35,  0,$FF,$36,$37,$38,$39,$FF,$3A,$3B,$3C
		.BYTE	$3D,  0,  0,$3E,$3F,$40,  0,  0,$41,$42,$43,  0,  0,$44,$45,$46
byte_5307D:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$34,$35,  0,  0,$36,$37,$38
		.BYTE	$39,  0,$3A,$3B,$3C,$3D,  0,  0,$66,$67,$40,  0,  0,$68,$69,$6A
byte_5309D:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,$34,$35
		.BYTE	  0,  0,$36,$37,$38,$39,  0,$3A,$3B,$3C,$3D,  0,  0,$6B,$6C,$6D
byte_530BD:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,$34,$35
		.BYTE	  0,  0,$54,$55,$56,$39,  0,$57,$58,$59,$3D,  0,  0,$6B,$6C,$6D
byte_530DD:
		.BYTE	  4,  6,$FF,$6E,$34,$35,  0,$FF,$6F,$70,$38,$39,$FF,  0,$71,$72
		.BYTE	$3D,  0,  0,$73,$3F,$40,  0,  0,$41,$42,$43,  0,  0,$44,$45,$46
byte_530FD:
		.BYTE	  4,  6,$FF,$74,$34,$35,  0,$FF,$75,$76,$38,$39,$FF,  0,$77,$78
		.BYTE	$3D,  0,  0,$73,$3F,$40,  0,  0,$41,$42,$43,  0,  0,$44,$45,$46
byte_5311D:
		.BYTE	  4,  6,$FF,  0,$34,$35,  0,$FF,  0,$79,$7A,$39,$FF,$7B,$7C,$7D
		.BYTE	$7E,  0,$7F,$80,$81,$40,  0,  0,$41,$42,$43,  0,  0,$44,$45,$46
byte_5313D:
		.BYTE	  4,  6,$FF,  0,$34,$35,  0,$FF,  0,$79,$82,$83,$FF,$7B,$84,$85
		.BYTE	$86,  0,  0,$87,$88,$40,  0,  0,$41,$42,$43,  0,  0,$44,$45,$46
byte_5315D:
		.BYTE	  4,  6,$FF,  0,$16,$17,  0,  1,  0,$18,$19,  0,  1,$1A,$1B,$1C
		.BYTE	  0,  0,  0,$32,$33,  0,  1,  0,$43,$35,  0,  1,  0,  0,  0,  0
byte_5317D:
		.BYTE	  2,  1,  0,$89,$8A
byte_53182:
		.BYTE	  2,  2,  0,$8B,$8C,  0,$8D,$8E
byte_5318A:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,$98,$99,$9A
byte_53198:
		.BYTE	  3,  3,  0,  0,  0,  0,  0,$9B,$9C,$9D,  0,$9E,$9F,$A0
byte_531A6:
		.BYTE	  3,  3,  0,$A1,$A2,$A3,  0,$A4,$A5,$A6,  0,$A7,$A8,$A9
byte_531B4:
		.BYTE	  3,  3,  0,$A1,$A2,$A3,  0,$AA,$A5,$A6,  0,$AB,$AC,$AD
byte_531C2:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$AE,$AF,  0,  0,  0,$B0,$B1
		.BYTE	  0,  0,  0,$B2,$B3,  0,  0,  0,$B4,$B5,  0,  0,  0,$B6,$B7,  0
byte_531E2:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$B8,$B9,  0,  0,  0,$BA,$BB
		.BYTE	  0,  0,  0,$BC,$BD,  0,  0,  0,$BE,$BF,$C0,  0,  0,$C1,$C2,$C3
byte_53202:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$AE,$AF,  0,  0,  0,$C4,$C5
		.BYTE	  0,  0,  0,$C6,$C7,  0,  0,  0,$C8,$B5,  0,  0,  0,$C9,$B7,  0
byte_53222:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$B8,$B9,  0,  0,  0,$BA,$BB
		.BYTE	  0,  0,  0,$CA,$CB,  0,  0,  0,$BE,$BF,$C0,  0,  0,$C1,$C2,$C3
byte_53242:
		.BYTE	  4,  6
		.BYTE	  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0
		.BYTE	  0,  0,$CC,$CD,  0
		.BYTE	  0,$CE,$CF,$D0,  0
		.BYTE	  0,$D1,$D2,$D3,  0
		.BYTE	  0,$D4,$D5,$D6,$D7
byte_53262:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,$CC,$CD
		.BYTE	  0,  0,$D8,$D9,$DA,  0,  0,$D1,$DB,$D3,  0,  0,$D4,$D5,$D6,$D7
byte_53282:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$DC,$DD,  0,  0,  0,$B0,$B1
		.BYTE	  0,  0,  0,$B2,$B3,  0,  0,  0,$B4,$B5,  0,  0,  0,$B6,$B7,  0
byte_532A2:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$DE,$DF,  0,  0,  0,$E0,$BB
		.BYTE	  0,  0,  0,$BC,$BD,  0,  0,  0,$BE,$BF,$C0,  0,  0,$C1,$C2,$C3
byte_532C2:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$DC,$DD,  0,  0,  0,$C4,$C5
		.BYTE	  0,  0,  0,$C6,$C7,  0,  0,  0,$C8,$B5,  0,  0,  0,$C9,$B7,  0
byte_532E2:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$DE,$DF,  0,  0,  0,$E0,$BB
		.BYTE	  0,  0,  0,$CA,$CB,  0,  0,  0,$BE,$BF,$C0,  0,  0,$C1,$C2,$C3
byte_53302:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,  0,$E1,$E2,$E3,  0,  0,$E4,$E5
		.BYTE	$E6,  0,$E7,$E8,$E9,$EA,  0,  0,$BE,$BF,  0,  0,  0,$C1,$C2,$C3
byte_53322:
		.BYTE	  4,  6,  0,  0,  0,  0,  0,  0,$EB,$EC,$ED,  0,  0,$EE,$EF,$F0
		.BYTE	  0,  0,  0,$F1,$F2,  0,  0,  0,$F3,$F4,  0,  0,  0,$C1,$F5,$F6
_spr_bbox_x_list:
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  8,  8,  8,  8,  8,  8,  8,  8,  0,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  0,  0,  0,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  0,  0,  8,  8,  8
		.BYTE	  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,$63,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
_spr_bbox_y_list:
		.BYTE	  0,  0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  8,$18,$18,  0,  0,  0,  0,  8,  8
		.BYTE	  0,  8,  0,  0,  0,  8,  0,  0,  8,  8,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  8,  8,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  8,  8,  8,  8,$10,  0,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  0,  0,  0,  0,  8,  8,  8,  8,  0,$10,  8,  8,  0,$10,  8
		.BYTE	  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  8,  8,  8,  8,  8,  8,$10,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  8,$18,$18,  0,  0,  0,  0,  0,  0,  0,  0,  8,  0
		.BYTE	  0,  8,  8,  8,  8,$10,$10,  8,  8,  8,  8,  8,  8,$63,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
_spr_bbox_width_list:
		.BYTE	  0,  8,$10,  4,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  8,  8,  8,$30,$30,$30,$30,$30,$30,$30,$30,$30,$30,$30,$30
		.BYTE	$30,$30,$30,$30,$30,$30,$30,$28,$18,$18,$30,$30,$30,$30,$28,$28
		.BYTE	  0,$10,$18,$18,  0,$10,$18,$18,$28,$28,$28,$28,$28,$28,$28,$28
		.BYTE	$28,$28,$28,$28,  0,$18,$18,$18,  0,$18,$18,$18,  0,$18,$18,$18
		.BYTE	  0,$18,$18,$18,$28,$28,$28,$28,$20,  8,$28,$28,$28,$28,$28,$28
		.BYTE	$28,$18,$18,$18,$18,$28,$28,$28,$28,  0,$10,$18,$18,  0,$10,$18
		.BYTE	$18,$28,$28,$28,$28,$28,$28,$28,$28,$28,$28,$28,$28,$28,$28,$28
		.BYTE	$28,$28,$28,$28,$28,$28,$28,$20,$20,$20,$20,$20,  0,  0,  0,  0
		.BYTE	  0,  4,  4,  8,$30,$30,$30,$30,$30,$30,$30,$30,$30,$30,  0,  0
		.BYTE	  0,  0,$30,$28,$18,$18,$30,$30,$30,$30,$30,  8,$10,  0,$10,$18
		.BYTE	$28,$28,$28,$28,$28,$20,$20,$28,$28,$28,$28,$28,$28,$28,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
_spr_bbox_height_list:
		.BYTE	  0,$10,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8
		.BYTE	  8,  8,  8,  8,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10
		.BYTE	$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$20,$20
		.BYTE	  0,$18,$18,$18,  0,$18,$18,$18,$20,$20,$20,$20,$20,$20,$20,$20
		.BYTE	$20,$20,$20,$20,  0,$18,$18,$18,  0,$18,$18,$18,  0,$18,$18,$18
		.BYTE	  0,$18,$18,$18,$20,$20,$20,$20,$20,$18,$10,$10,$10,$10,$10,$10
		.BYTE	$10,$10,$10,$10,$10,$10,$10,$10,$10,  0,$10,$10,$10,  0,$10,$10
		.BYTE	$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10
		.BYTE	$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,  0,  0,  0,  0
		.BYTE	  0,  8,  8,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10
		.BYTE	$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,  0,$10,$10
		.BYTE	$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,$10,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
		.BYTE	  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
